create_clock -period 20.000 -name crystal_clk_50mhz -waveform {0.000 10.000} [get_ports crystal_clk_50mhz]

set_property IOSTANDARD LVCMOS33 [get_ports crystal_clk_50mhz]
set_property PACKAGE_PIN U18 [get_ports crystal_clk_50mhz]
set_property IOSTANDARD LVCMOS33 [get_ports adc_clk_0]
set_property PACKAGE_PIN R14 [get_ports dac_clk_0]
set_property IOSTANDARD LVCMOS33 [get_ports dac_clk_0]
set_property PACKAGE_PIN N15 [get_ports key_reset_0]
set_property IOSTANDARD LVCMOS25 [get_ports key_reset_0]

set_property IOSTANDARD LVCMOS25 [get_ports LED1]

set_property IOSTANDARD LVCMOS25 [get_ports LED2]

set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_input_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_input_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_input_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_input_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_input_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_input_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_input_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_input_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_out_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_out_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_out_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_out_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_out_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_out_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_out_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_out_0[0]}]
set_property PACKAGE_PIN V17 [get_ports {adc_data_input_0[1]}]
set_property PACKAGE_PIN T15 [get_ports {adc_data_input_0[2]}]
set_property PACKAGE_PIN T14 [get_ports {adc_data_input_0[3]}]
set_property PACKAGE_PIN V13 [get_ports {adc_data_input_0[4]}]
set_property PACKAGE_PIN U13 [get_ports {adc_data_input_0[5]}]
set_property PACKAGE_PIN W13 [get_ports {adc_data_input_0[6]}]
set_property PACKAGE_PIN V12 [get_ports {adc_data_input_0[7]}]
set_property PACKAGE_PIN P18 [get_ports {dac_data_out_0[0]}]
set_property PACKAGE_PIN W14 [get_ports {dac_data_out_0[1]}]
set_property PACKAGE_PIN Y14 [get_ports {dac_data_out_0[2]}]
set_property PACKAGE_PIN V15 [get_ports {dac_data_out_0[3]}]
set_property PACKAGE_PIN W15 [get_ports {dac_data_out_0[4]}]
set_property PACKAGE_PIN Y16 [get_ports {dac_data_out_0[5]}]
set_property PACKAGE_PIN Y17 [get_ports {dac_data_out_0[6]}]
set_property PACKAGE_PIN P14 [get_ports {dac_data_out_0[7]}]
set_property PACKAGE_PIN T17 [get_ports key_freq_sel_0]
set_property PACKAGE_PIN R17 [get_ports key_wave_sel_0]
set_property IOSTANDARD LVCMOS25 [get_ports key_extract_sel_0]
set_property IOSTANDARD LVCMOS33 [get_ports key_freq_sel_0]
set_property IOSTANDARD LVCMOS33 [get_ports key_wave_sel_0]




set_property IOSTANDARD LVDS_25 [get_ports {CLK_OUT_D3_0_clk_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {CLK_OUT_D3_0_clk_n[0]}]
set_property PACKAGE_PIN V18 [get_ports {adc_data_input_0[0]}]
set_property PACKAGE_PIN U12 [get_ports adc_clk_0]
set_property PACKAGE_PIN N16 [get_ports key_extract_sel_0]
set_property PACKAGE_PIN F19 [get_ports {CLK_OUT_D3_0_clk_p[0]}]
set_property PACKAGE_PIN J18 [get_ports {data_in_from_pins_p_0[0]}]
set_property PACKAGE_PIN L19 [get_ports {data_in_from_pins_p_0[1]}]
set_property PACKAGE_PIN M19 [get_ports {data_in_from_pins_p_0[2]}]
set_property PACKAGE_PIN K19 [get_ports {data_in_from_pins_p_0[4]}]
set_property PACKAGE_PIN J20 [get_ports {data_in_from_pins_p_0[5]}]
set_property PACKAGE_PIN L16 [get_ports {data_in_from_pins_p_0[6]}]
set_property PACKAGE_PIN M17 [get_ports {data_in_from_pins_p_0[7]}]
set_property PACKAGE_PIN D19 [get_ports {data_in_from_pins_p_0[8]}]
set_property PACKAGE_PIN E18 [get_ports {data_in_from_pins_p_0[9]}]
set_property PACKAGE_PIN G17 [get_ports {data_in_from_pins_p_0[10]}]
set_property PACKAGE_PIN H16 [get_ports {data_in_from_pins_p_0[11]}]
set_property PACKAGE_PIN H15 [get_ports {data_in_from_pins_p_0[3]}]
set_property PACKAGE_PIN M14 [get_ports LED1]
set_property PACKAGE_PIN M15 [get_ports LED2]
set_property PACKAGE_PIN K17 [get_ports diff_clk_in_0_clk_p]
set_property IOSTANDARD LVDS_25 [get_ports diff_clk_in_0_clk_p]
set_property IOSTANDARD LVDS_25 [get_ports diff_clk_in_0_clk_n]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets dac_clk_0_OBUF]
